### ISSUE TITLE
Query about adding multiple actions

### ISSUE THREAD

**Issue by sparkcanon** [lifepillar/vim-zeef#1]
I am looking to create a buffer list where I can open a buffer, delete the buffer, and override the key mappings. I am unsure as to how do I go about doing that. Below is a test implementation(largely from your sample), can you help me identify what I am doing wrong?

```
let g:zeef_keymap = {
			\ 'ctrl-d': function('DeleteBuf')
			\ }

fun! Buffers() abort
	let l:items = map(split(execute('ls' .. (get({ 'unlisted': 0 }, 'unlisted', 0) ? '!' : '')), "\n"), 'substitute(v:val, ''"\(.*\)"\s*line\s*\d\+$'', ''\1'', "")')
	call zeef#open(l:items, 'Callback', 'choose')
endfun

fun! Callback(result) abort
	execute 'buffer' . a:result
endfun

fun! DeleteBuf(result) abort
	execute 'bdelete' . a:result
endfun
```

**Comment by lifepillar** [comment]
You should delete the buffers in your callback. Think of it this way: Zeef's role is just to take a list as input and return a (sub)list to a callback; then the callback does whatever you want with that sublist. So, try something like this instead of your code (untested):

```vim
fun! Buffers() abort
	let l:items = map(split(execute('ls' .. (get({ 'unlisted': 0 }, 'unlisted', 0) ? '!' : '')), "\n"), 'substitute(v:val, ''"\(.*\)"\s*line\s*\d\+$'', ''\1'', "")')
	call zeef#open(l:items, 'Callback', 'choose')
endfun

fun! Callback(result) abort
	for l:buffer in a:result
		execute "bdelete" matchstr(l:buffer, '^\s*\zs\d\+')
	endfor
endfun
``` 

Then, in your `vimrc` you may add a mapping to call `Buffers()`, e.g.:

```vim
nmap <c-d> :<c-u>call Buffers()<cr>
```

Now, you can type CTRL-D to open Zeef, select the buffers to delete with CTRL-Z, and press Enter to delete them.

**Comment by lifepillar** [comment]
>I am looking to create a buffer list where I can open a buffer, delete the buffer, and override the key mappings.

There is no straightforward way to do that, currently. For that, you should be able to distinguish, in your callback function, which key was used to dismiss Zeef. But I may add a variable or a function that returns such key.

**Comment by lifepillar** [comment]
With the current master, you may now write something like this:

```vim
let g:zeef_keymap = {
      \ "\<c-d>": function('zeef#accept')
      \ }

fun! Buffers() abort
	let l:items = map(split(execute('ls' .. (get({ 'unlisted': 0 }, 'unlisted', 0) ? '!' : '')), "\n"), 'substitute(v:val, ''"\(.*\)"\s*line\s*\d\+$'', ''\1'', "")')
	call zeef#open(l:items, 'Callback', 'choose')
endfun

fun! Callback(result) abort
  if zeef#keypressed() == "\<c-d>"
    echo "Delete: " .. join(a:result)
  else
    echo "Do smth else with " .. join(a:result)
  endif
endfun
```

`zeef#keypressed()` is a new function that returns the last key pressed. The logic of the action to perform can thus be managed by the callback based on the key pressed to accept the current choice.

Alternatively, you may now manage the result in your own function, e.g.:

```vim
fun! DeleteBuf()
  call zeef#close('')           " Close Zeef
  let l:result = zeef#result()  " Retrieve the filtered list
  for l:item in l:result
    echo "Delete " .. l:item
  endfor
  return 1  " It MUST return 1
endf

let g:zeef_keymap = {
      \ "\<c-d>": function('DeleteBuf')
      \ }

fun! Buffers() abort
  let l:items = map(split(execute('ls' .. (get({ 'unlisted': 0 }, 'unlisted', 0) ? '!' : '')), "\n"), 'substitute(v:val, ''"\(.*\)"\s*line\s*\d\+$'', ''\1'', "")')
  call zeef#open(l:items, 'Callback', 'choose')
endfun

fun! Callback(result) abort
  echo "Do smth else with result"
endfun
```

In this case, the callback handles some default behaviour, and you may define your own mappings (via `g:zeef_keymap`) to execute alternative actions, such as `DeleteBuf()`. Note that `DeleteBuf()` has to explicitly close the Zeef buffer and retrieve the filtered list via a newly added function `zeef#result()`. This is closer to what you were trying to achieve.

Hope this helps!

**Comment by lifepillar** [comment]
En passant, I'd like to mention [vim-select](https://github.com/habamax/vim-select), which seems to follow the same “no bloat” philosophy as Zeef. You might find it better for your use case.

**Comment by sparkcanon** [comment]
Thanks for taking a look at this. The first option works very well for me.

One thing to note here though, if I add or override `g:zeef_keymap` that will affect all use cases unless I manually disable them in the callbacks for each scenario. Please correct me if I am wrong here.

I have seen vim-select, it is indeed very nice. Although I was quite enamored with [quickpick](https://github.com/prabirshrestha/quickpick.vim) as well.

**Comment by lifepillar** [comment]
You're right, the keymap is global. Adding a hook for buffer-local overrides may be possible without much effort. I'll take a look.

>I was quite enamored with quickpick as well.

Wow, this space is crowded 😀

**Comment by lifepillar** [comment]
With the current master, you may rewrite the above as follows:

```vim
	fun! Buffers() abort
	  let l:buffers = split(execute('ls'), "\n")
	  call zeef#open(l:buffers, 'Callback', 'Choose', { "\<c-d>": function('zeef#accept') })
	endfun

	fun! Callback(result) abort
	  if zeef#keypressed() == "\<c-d>"
	    for l:item in a:result
	      echo ":bdelete " .. matchstr(l:item, '^\s*\zs\d\+')
	    endfor
	  else
	    echo "Do smth else with the result"
	  endif
	endfun

	:call Buffers()
```

Note the custom mapping passed to zeef#open(). The custom CTRL-D mapping applies only to `Buffers()`.

Hope this helps!

**Comment by sparkcanon** [comment]
This works perfectly for my use case, thanks for taking the time to do this.
